### ISSUE TITLE
Cloudwatchmetricbeat stoppes after first request without any errors

### ISSUE THREAD

**Issue by laboshinl** [narmitech/cloudwatchmetricbeat#3]
Could you please help me on this. Cannot use beat properly. It fails after first request.
Thanks in advance,
Leonid
```
root@elk:~/go/src/github.com/narmitech/cloudwatchmetricbeat# cloudwatchmetricbeat -c cloudwatchmetricbeat.yml -e -d "*"
2018/05/14 14:26:16.042086 beat.go:285: INFO Home path: [/root/go/src/github.com/narmitech/cloudwatchmetricbeat] Config path: [/root/go/src/github.com/narmitech/cloudwatchmetricbeat] Data path: [/root/go/src/github.com/narmitech/cloudwatchmetricbeat/data] Logs path: [/root/go/src/github.com/narmitech/cloudwatchmetricbeat/logs]
2018/05/14 14:26:16.044414 beat.go:186: INFO Setup Beat: cloudwatchmetricbeat; Version: 5.3.4
2018/05/14 14:26:16.044429 processor.go:44: DBG  Processors:
2018/05/14 14:26:16.044442 beat.go:192: DBG  Initializing output plugins
2018/05/14 14:26:16.044509 output.go:254: INFO Loading template enabled. Reading template file: /root/go/src/github.com/narmitech/cloudwatchmetricbeat/cloudwatchmetricbeat.template.json
2018/05/14 14:26:16.044650 output.go:265: INFO Loading template enabled for Elasticsearch 2.x. Reading template file: /root/go/src/github.com/narmitech/cloudwatchmetricbeat/cloudwatchmetricbeat.template-es2x.json
2018/05/14 14:26:16.044796 client.go:123: INFO Elasticsearch url: http://localhost:9200
2018/05/14 14:26:16.044828 outputs.go:108: INFO Activated elasticsearch as output plugin.
2018/05/14 14:26:16.044848 publish.go:238: DBG  Create output worker
2018/05/14 14:26:16.044886 publish.go:280: DBG  No output is defined to store the topology. The server fields might not be filled.
2018/05/14 14:26:16.044909 publish.go:295: INFO Publisher name: elk
2018/05/14 14:26:16.045031 async.go:63: INFO Flush Interval set to: 1s
2018/05/14 14:26:16.045050 async.go:64: INFO Max Bulk Size set to: 50
2018/05/14 14:26:16.045058 async.go:72: DBG  create bulk processing worker (interval=1s, bulk size=50)
2018/05/14 14:26:16.045268 cloudwatchmetricbeat.go:44: INFO settings: config={Period:1m0s AWSRegion:us-east-1 Prospectors:[{Id:billing Metrics:[{AWSStatistics:[Maximum] AWSDimensions:[Currency] AWSDimensionSelect:map[Currency:[USD]] AWSDimensionsSelectParam:map[] AWSNamespace:AWS/Billing AWSMetricName:EstimatedCharges RangeSeconds:86400 PeriodSeconds:0 DelaySeconds:0}]} {Id:ec2_cloudwatch Metrics:[{AWSStatistics:[Average] AWSDimensions:[InstanceId] AWSDimensionSelect:map[InstanceId:[id-09005aa854cb13b23]] AWSDimensionsSelectParam:map[] AWSNamespace:AWS/EC2 AWSMetricName:CPUUtilization RangeSeconds:0 PeriodSeconds:0 DelaySeconds:0} {AWSStatistics:[Average] AWSDimensions:[InstanceId] AWSDimensionSelect:map[InstanceId:[id-09005aa854cb13b23]] AWSDimensionsSelectParam:map[] AWSNamespace:AWS/EC2 AWSMetricName:NetworkOut RangeSeconds:0 PeriodSeconds:0 DelaySeconds:0}]} {Id:vpn_mon Metrics:[{AWSStatistics:[Average] AWSDimensions:[VpnId] AWSDimensionSelect:map[VpnId:[vpn-61687a11]] AWSDimensionsSelectParam:map[] AWSNamespace:AWS/VPN AWSMetricName:TunnelState RangeSeconds:3600 PeriodSeconds:0 DelaySeconds:0}]}]}
2018/05/14 14:26:16.045381 beat.go:221: INFO cloudwatchmetricbeat start running.
2018/05/14 14:26:16.045392 cloudwatchmetricbeat.go:63: INFO cloudwatchmetricbeat is running! Hit CTRL-C to stop it.
2018/05/14 14:26:16.045424 metrics.go:23: INFO Metrics logging every 30s
2018/05/14 14:26:46.045680 metrics.go:34: INFO No non-zero metrics in the last 30s
2018/05/14 14:27:16.045624 metrics.go:34: INFO No non-zero metrics in the last 30s
2018/05/14 14:27:16.175219 cloudwatchmetricbeat.go:194: INFO making request: params={
  Dimensions: [{
      Name: "VpnId",
      Value: "vpn-61687a11"
    }],
  EndTime: 2018-05-14 14:22:16.045654982 +0000 UTC,
  MetricName: "TunnelState",
  Namespace: "AWS/VPN",
  Period: 60,
  StartTime: 2018-05-14 13:22:16.045654982 +0000 UTC,
  Statistics: ["Average"]
}
2018/05/14 14:27:16.175281 metrics.go:51: INFO Total non-zero values:
2018/05/14 14:27:16.175293 metrics.go:52: INFO Uptime: 1m0.136432267s
2018/05/14 14:27:16.175301 beat.go:225: INFO cloudwatchmetricbeat stopped.
```

**Comment by phillbaker** [comment]
Hi @laboshinl can you share your beat config (with sensitive information redacted)? 

Offhand, it sounds like your period config parameter for the beat is set to zero, which will run once and exit as you're describing. The example config uses 60 seconds, e.g.:

https://github.com/narmitech/cloudwatchmetricbeat/blob/bbd41f4ad332b6c28c28f39254b2e6261fec9c30/_meta/beat.yml#L10

**Comment by laboshinl** [comment]
I've followed instructions from Dockerfile so my cloudwatchmetricbeat.yml is just a copy of default beat.yml from _meta folder

**Comment by laboshinl** [comment]
I've adjusted AWS credentials and instance id in  .yml and it able to get metric, but then exits
```
2018/05/14 14:11:15.385975 client.go:214: DBG  Publish: {
  "@timestamp": "2018-05-14T14:03:00.000Z",
  "beat": {
    "hostname": "elk",
    "name": "elk",
    "version": "5.3.4"
  },
  "cloudwatchset.name": "ec2_cloudwatch",
  "cloudwatchset.namespace": "AWS/EC2",
  "cloudwatchset.resource_id": "i-00c115654853da100",
  "cloudwatchset.resource_id_type": "instance_id",
  "cpu_utilization.avg": 73.394975,
  "type": "cloudwatchset"
}
2018/05/14 14:11:15.386038 metrics.go:51: INFO Total non-zero values:  libbeat.publisher.messages_in_worker_queues=1 libbeat.publisher.published_events=1
2018/05/14 14:11:15.386050 metrics.go:52: INFO Uptime: 1m0.095071986s
2018/05/14 14:11:15.386055 beat.go:225: INFO cloudwatchmetricbeat stopped.
```

**Comment by laboshinl** [comment]
```
@elk:/etc/cloudwatchmetricbeat# uname -a
Linux elk 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
@elk:/etc/cloudwatchmetricbeat# cat /etc/debian_version
stretch/sid
@elk:/etc/cloudwatchmetricbeat# go version
go version go1.7.1 linux/amd64
@elk:/etc/cloudwatchmetricbeat# glide -version
glide version 0.10.2
```
The version of cloudwatchmetricbeat is v0.1.7 ( I.ve also tried to build from master branch with the same result)

**Comment by laboshinl** [comment]
Same on centos 7

```yaml
################### Cloudwatchmetricbeat Configuration Example #########################

############################# Cloudwatchmetricbeat ######################################

cloudwatchmetricbeat:

  # === GENERAL SETTINGS ===

  # How often to query the api for metrics (default: 60s)
  period: 60
  period_seconds: 60
  aws_region: us-east-1

  # === PROSPECTORS ===
  # Applications whose log groups we'd like to monitor
  prospectors:
    - id: ec2_cloudwatch
      metrics:
        - aws_namespace: "AWS/EC2"
          aws_dimensions: [InstanceId]
          period_seconds: 60
          aws_dimensions_select:
            InstanceId: [i-07a27a3fb38cc4683]
          aws_metric_name: CPUUtilization
          aws_statistics: [Average]


#================================ General ======================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
# If this options is not defined, the hostname is used.
#name:

# The tags of the shipper are included in their own field with each
# transaction published. Tags make it easy to group servers by different
# logical properties.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output. Fields can be scalar values, arrays, dictionaries, or any nested
# combination of these.
#fields:
#  env: staging

# If this option is set to true, the custom fields are stored as top-level
# fields in the output document instead of being grouped under a fields
# sub-dictionary. Default is false.
#fields_under_root: false

# Internal queue size for single events in processing pipeline
#queue_size: 1000

# The internal queue size for bulk events in the processing pipeline.
# Do not modify this value.
#bulk_queue_size: 0

# Sets the maximum number of CPUs that can be executing simultaneously. The
# default is the number of logical CPUs available in the system.
#max_procs:

#================================ Processors ===================================

# Processors are used to reduce the number of fields in the exported event or to
# enhance the event with external metadata. This section defines a list of
# processors that are applied one by one and the first one receives the initial
# event:
#
#   event -> filter1 -> event1 -> filter2 ->event2 ...
#
# The supported processors are drop_fields, drop_event, include_fields, and
# add_cloud_metadata.
#
# For example, you can use the following processors to keep the fields that
# contain CPU load percentages, but remove the fields that contain CPU ticks
# values:
#
#processors:
#- include_fields:
#    fields: ["cpu"]
#- drop_fields:
#    fields: ["cpu.user", "cpu.system"]
#
# The following example drops the events that have the HTTP response code 200:
#
#processors:
#- drop_event:
#    when:
#       equals:
#           http.code: 200
#
# The following example enriches each event with metadata from the cloud
# provider about the host machine. It works on EC2, GCE, and DigitalOcean.
#
#processors:
#- add_cloud_metadata:
#

#================================ Outputs ======================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # Array of hosts to connect to.
  # Scheme and port can be left out and will be set to the default (http and 9200)
  # In case you specify and additional path, the scheme is required: http://localhost:9200/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
  hosts: ["localhost:9200"]

  # Set gzip compression level.
  #compression_level: 0

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

  # Dictionary of HTTP parameters to pass within the url with index operations.
  #parameters:
    #param1: value1
    #param2: value2

  # Number of workers per Elasticsearch host.
  #worker: 1

  # Optional index name. The default is "cloudwatchmetricbeat" plus date
  # and generates [cloudwatchmetricbeat-]YYYY.MM.DD keys.
  #index: "cloudwatchmetricbeat-%{+yyyy.MM.dd}"

  # Optional ingest node pipeline. By default no pipeline will be used.
  #pipeline: ""

  # Optional HTTP Path
  #path: "/elasticsearch"

  # Proxy server url
  #proxy_url: http://proxy:3128

  # The number of times a particular Elasticsearch index operation is attempted. If
  # the indexing operation doesn't succeed after this many retries, the events are
  # dropped. The default is 3.
  #max_retries: 3

  # The maximum number of events to bulk in a single Elasticsearch bulk API index request.
  # The default is 50.
  #bulk_max_size: 50

  # Configure http request timeout before failing an request to Elasticsearch.
  #timeout: 90

  # The number of seconds to wait for new events between two bulk API index requests.
  # If `bulk_max_size` is reached before this interval expires, addition bulk index
  # requests are made.
  #flush_interval: 1s

  # A template is used to set the mapping in Elasticsearch
  # By default template loading is enabled and the template is loaded.
  # These settings can be adjusted to load your own template or overwrite existing ones.

  # Set to false to disable template loading.
  #template.enabled: true

  # Template name. By default the template name is cloudwatchmetricbeat.
  #template.name: "cloudwatchmetricbeat"

  # Path to template file
  #template.path: "${path.config}/cloudwatchmetricbeat.template.json"

  # Overwrite existing template
  template.overwrite: true

  # If set to true, cloudwatchmetricbeat checks the Elasticsearch version at connect time, and if it
  # is 2.x, it loads the file specified by the template.versions.2x.path setting. The
  # default is true.
  #template.versions.2x.enabled: true

  # Path to the Elasticsearch 2.x version of the template file.
  #template.versions.2x.path: "${path.config}/cloudwatchmetricbeat.template-es2x.json"

  # Use SSL settings for HTTPS. Default is true.
  #ssl.enabled: true

  # Configure SSL verification mode. If `none` is configured, all server hosts
  # and certificates will be accepted. In this mode, SSL based connections are
  # susceptible to man-in-the-middle attacks. Use only for testing. Default is
  # `full`.
  #ssl.verification_mode: full

  # List of supported/valid TLS versions. By default all TLS versions 1.0 up to
  # 1.2 are enabled.
  #ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]

  # SSL configuration. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

  # Optional passphrase for decrypting the Certificate Key.
  #ssl.key_passphrase: ''

  # Configure cipher suites to be used for SSL connections
  #ssl.cipher_suites: []

  # Configure curve types for ECDHE based cipher suites
  #ssl.curve_types: []


#----------------------------- Logstash output ---------------------------------
#output.logstash:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Number of workers per Logstash host.
  #worker: 1

  # Set gzip compression level.
  #compression_level: 3

  # Optional load balance the events between the Logstash hosts
  #loadbalance: true

  # Number of batches to be send asynchronously to logstash while processing
  # new batches.
  #pipelining: 0

  # Optional index name. The default index name is set to name of the beat
  # in all lowercase.
  #index: 'cloudwatchmetricbeat'

  # SOCKS5 proxy server URL
  #proxy_url: socks5://user:password@socks5-server:2233

  # Resolve names locally when using a proxy server. Defaults to false.
  #proxy_use_local_resolver: false

  # Enable SSL support. SSL is automatically enabled, if any SSL setting is set.
  #ssl.enabled: true

  # Configure SSL verification mode. If `none` is configured, all server hosts
  # and certificates will be accepted. In this mode, SSL based connections are
  # susceptible to man-in-the-middle attacks. Use only for testing. Default is
  # `full`.
  #ssl.verification_mode: full

  # List of supported/valid TLS versions. By default all TLS versions 1.0 up to
  # 1.2 are enabled.
  #ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]

  # Optional SSL configuration options. SSL is off by default.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

  # Optional passphrase for decrypting the Certificate Key.
  #ssl.key_passphrase: ''

  # Configure cipher suites to be used for SSL connections
  #ssl.cipher_suites: []

  # Configure curve types for ECDHE based cipher suites
  #ssl.curve_types: []

#------------------------------- Kafka output ----------------------------------
#output.kafka:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # The list of Kafka broker addresses from where to fetch the cluster metadata.
  # The cluster metadata contain the actual Kafka brokers events are published
  # to.
  #hosts: ["localhost:9092"]

  # The Kafka topic used for produced events. The setting can be a format string
  # using any event field. To set the topic from document type use `%{[type]}`.
  #topic: beats

  # The Kafka event key setting. Use format string to create unique event key.
  # By default no event key will be generated.
  #key: ''

  # The Kafka event partitioning strategy. Default hashing strategy is `hash`
  # using the `output.kafka.key` setting or randomly distributes events if
  # `output.kafka.key` is not configured.
  #partition.hash:
    # If enabled, events will only be published to partitions with reachable
    # leaders. Default is false.
    #reachable_only: false

    # Configure alternative event field names used to compute the hash value.
    # If empty `output.kafka.key` setting will be used.
    # Default value is empty list.
    #hash: []

  # Authentication details. Password is required if username is set.
  #username: ''
  #password: ''

  # Kafka version cloudwatchmetricbeat is assumed to run against. Defaults to the oldest
  # supported stable version (currently version 0.8.2.0)
  #version: 0.8.2

  # Metadata update configuration. Metadata do contain leader information
  # deciding which broker to use when publishing.
  #metadata:
    # Max metadata request retry attempts when cluster is in middle of leader
    # election. Defaults to 3 retries.
    #retry.max: 3

    # Waiting time between retries during leader elections. Default is 250ms.
    #retry.backoff: 250ms

    # Refresh metadata interval. Defaults to every 10 minutes.
    #refresh_frequency: 10m

  # The number of concurrent load-balanced Kafka output workers.
  #worker: 1

  # The number of times to retry publishing an event after a publishing failure.
  # After the specified number of retries, the events are typically dropped.
  # Some Beats, such as Filebeat, ignore the max_retries setting and retry until
  # all events are published.  Set max_retries to a value less than 0 to retry
  # until all events are published. The default is 3.
  #max_retries: 3

  # The maximum number of events to bulk in a single Kafka request. The default
  # is 2048.
  #bulk_max_size: 2048

  # The number of seconds to wait for responses from the Kafka brokers before
  # timing out. The default is 30s.
  #timeout: 30s

  # The maximum duration a broker will wait for number of required ACKs. The
  # default is 10s.
  #broker_timeout: 10s

  # The number of messages buffered for each Kafka broker. The default is 256.
  #channel_buffer_size: 256

  # The keep-alive period for an active network connection. If 0s, keep-alives
  # are disabled. The default is 0 seconds.
  #keep_alive: 0

  # Sets the output compression codec. Must be one of none, snappy and gzip. The
  # default is gzip.
  #compression: gzip

  # The maximum permitted size of JSON-encoded messages. Bigger messages will be
  # dropped. The default value is 1000000 (bytes). This value should be equal to
  # or less than the broker's message.max.bytes.
  #max_message_bytes: 1000000

  # The ACK reliability level required from broker. 0=no response, 1=wait for
  # local commit, -1=wait for all replicas to commit. The default is 1.  Note:
  # If set to 0, no ACKs are returned by Kafka. Messages might be lost silently
  # on error.
  #required_acks: 1

  # The number of seconds to wait for new events between two producer API calls.
  #flush_interval: 1s

  # The configurable ClientID used for logging, debugging, and auditing
  # purposes.  The default is "beats".
  #client_id: beats

  # Enable SSL support. SSL is automatically enabled, if any SSL setting is set.
  #ssl.enabled: true

  # Optional SSL configuration options. SSL is off by default.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Configure SSL verification mode. If `none` is configured, all server hosts
  # and certificates will be accepted. In this mode, SSL based connections are
  # susceptible to man-in-the-middle attacks. Use only for testing. Default is
  # `full`.
  #ssl.verification_mode: full

  # List of supported/valid TLS versions. By default all TLS versions 1.0 up to
  # 1.2 are enabled.
  #ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

  # Optional passphrase for decrypting the Certificate Key.
  #ssl.key_passphrase: ''

  # Configure cipher suites to be used for SSL connections
  #ssl.cipher_suites: []

  # Configure curve types for ECDHE based cipher suites
  #ssl.curve_types: []

#------------------------------- Redis output ----------------------------------
#output.redis:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # The list of Redis servers to connect to. If load balancing is enabled, the
  # events are distributed to the servers in the list. If one server becomes
  # unreachable, the events are distributed to the reachable servers only.
  #hosts: ["localhost:6379"]

  # The Redis port to use if hosts does not contain a port number. The default
  # is 6379.
  #port: 6379

  # The name of the Redis list or channel the events are published to. The
  # default is cloudwatchmetricbeat.
  #key: cloudwatchmetricbeat

  # The password to authenticate with. The default is no authentication.
  #password:

  # The Redis database number where the events are published. The default is 0.
  #db: 0

  # The Redis data type to use for publishing events. If the data type is list,
  # the Redis RPUSH command is used. If the data type is channel, the Redis
  # PUBLISH command is used. The default value is list.
  #datatype: list

  # The number of workers to use for each host configured to publish events to
  # Redis. Use this setting along with the loadbalance option. For example, if
  # you have 2 hosts and 3 workers, in total 6 workers are started (3 for each
  # host).
  #worker: 1

  # If set to true and multiple hosts or workers are configured, the output
  # plugin load balances published events onto all Redis hosts. If set to false,
  # the output plugin sends all events to only one host (determined at random)
  # and will switch to another host if the currently selected one becomes
  # unreachable. The default value is true.
  #loadbalance: true

  # The Redis connection timeout in seconds. The default is 5 seconds.
  #timeout: 5s

  # The number of times to retry publishing an event after a publishing failure.
  # After the specified number of retries, the events are typically dropped.
  # Some Beats, such as Filebeat, ignore the max_retries setting and retry until
  # all events are published. Set max_retries to a value less than 0 to retry
  # until all events are published. The default is 3.
  #max_retries: 3

  # The maximum number of events to bulk in a single Redis request or pipeline.
  # The default is 2048.
  #bulk_max_size: 2048

  # The URL of the SOCKS5 proxy to use when connecting to the Redis servers. The
  # value must be a URL with a scheme of socks5://.
  #proxy_url:

  # This option determines whether Redis hostnames are resolved locally when
  # using a proxy. The default value is false, which means that name resolution
  # occurs on the proxy server.
  #proxy_use_local_resolver: false

  # Enable SSL support. SSL is automatically enabled, if any SSL setting is set.
  #ssl.enabled: true

  # Configure SSL verification mode. If `none` is configured, all server hosts
  # and certificates will be accepted. In this mode, SSL based connections are
  # susceptible to man-in-the-middle attacks. Use only for testing. Default is
  # `full`.
  #ssl.verification_mode: full

  # List of supported/valid TLS versions. By default all TLS versions 1.0 up to
  # 1.2 are enabled.
  #ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]

  # Optional SSL configuration options. SSL is off by default.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

  # Optional passphrase for decrypting the Certificate Key.
  #ssl.key_passphrase: ''

  # Configure cipher suites to be used for SSL connections
  #ssl.cipher_suites: []

  # Configure curve types for ECDHE based cipher suites
  #ssl.curve_types: []


#------------------------------- File output -----------------------------------
#output.file:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # Path to the directory where to save the generated files. The option is
  # mandatory.
  #path: "/tmp/cloudwatchmetricbeat"

  # Name of the generated files. The default is `cloudwatchmetricbeat` and it generates
  # files: `cloudwatchmetricbeat`, `cloudwatchmetricbeat.1`, `cloudwatchmetricbeat.2`, etc.
  #filename: cloudwatchmetricbeat

  # Maximum size in kilobytes of each file. When this size is reached, and on
  # every cloudwatchmetricbeat restart, the files are rotated. The default value is 10240
  # kB.
  #rotate_every_kb: 10000

  # Maximum number of files under path. When this number of files is reached,
  # the oldest file is deleted and the rest are shifted from last to first. The
  # default is 7 files.
  #number_of_files: 7


#----------------------------- Console output ---------------------------------
#output.console:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # Pretty print json event
  #pretty: false

#================================= Paths ======================================

# The home path for the cloudwatchmetricbeat installation. This is the default base path
# for all other path settings and for miscellaneous files that come with the
# distribution (for example, the sample dashboards).
# If not set by a CLI flag or in the configuration file, the default for the
# home path is the location of the binary.
#path.home:

# The configuration path for the cloudwatchmetricbeat installation. This is the default
# base path for configuration files, including the main YAML configuration file
# and the Elasticsearch template file. If not set by a CLI flag or in the
# configuration file, the default for the configuration path is the home path.
#path.config: ${path.home}

# The data path for the cloudwatchmetricbeat installation. This is the default base path
# for all the files in which cloudwatchmetricbeat needs to store its data. If not set by a
# CLI flag or in the configuration file, the default for the data path is a data
# subdirectory inside the home path.
#path.data: ${path.home}/data

# The logs path for a cloudwatchmetricbeat installation. This is the default location for
# the Beat's log files. If not set by a CLI flag or in the configuration file,
# the default for the logs path is a logs subdirectory inside the home path.
#path.logs: ${path.home}/logs

#================================ Logging ======================================
# There are three options for the log output: syslog, file, stderr.
# Under Windows systems, the log files are per default sent to the file output,
# under all other system per default to syslog.

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
#logging.level: info

# Enable debug output for selected components. To enable all selectors use ["*"]
# Other available selectors are "beat", "publish", "service"
# Multiple selectors can be chained.
#logging.selectors: [ ]

# Send all logging output to syslog. The default is false.
#logging.to_syslog: true

# If enabled, cloudwatchmetricbeat periodically logs its internal metrics that have changed
# in the last period. For each metric that changed, the delta from the value at
# the beginning of the period is logged. Also, the total values for
# all non-zero internal metrics are logged on shutdown. The default is true.
#logging.metrics.enabled: true

# The period after which to log the internal metrics. The default is 30s.
#logging.metrics.period: 30s

# Logging to rotating files files. Set logging.to_files to false to disable logging to
# files.
logging.to_files: true
logging.files:
  # Configure the path where the logs are written. The default is the logs directory
  # under the home path (the binary location).
  #path: /var/log/cloudwatchmetricbeat

  # The name of the files where the logs are written to.
  #name: cloudwatchmetricbeat

  # Configure log file size limit. If limit is reached, log file will be
  # automatically rotated
  #rotateeverybytes: 10485760 # = 10MB

  # Number of rotated log files to keep. Oldest files will be deleted first.
  #keepfiles: 7
```

```
cloudwatchmetricbeat -c cloudwatchmetricbeat.yml -e -d "*"
2018/05/15 11:12:40.396280 beat.go:285: INFO Home path: [/etc/cloudwatchmetricbeat] Config path: [/etc/cloudwatchmetricbeat] Data path: [/etc/cloudwatchmetricbeat/data] Logs path: [/etc/cloudwatchmetricbeat/logs]
2018/05/15 11:12:40.396306 beat.go:186: INFO Setup Beat: cloudwatchmetricbeat; Version: 5.3.4
2018/05/15 11:12:40.396317 processor.go:44: DBG  Processors:
2018/05/15 11:12:40.396327 beat.go:192: DBG  Initializing output plugins
2018/05/15 11:12:40.396461 output.go:254: INFO Loading template enabled. Reading template file: /etc/cloudwatchmetricbeat/cloudwatchmetricbeat.template.json
2018/05/15 11:12:40.396605 output.go:265: INFO Loading template enabled for Elasticsearch 2.x. Reading template file: /etc/cloudwatchmetricbeat/cloudwatchmetricbeat.template-es2x.json
2018/05/15 11:12:40.396762 client.go:123: INFO Elasticsearch url: http://localhost:9200
2018/05/15 11:12:40.396792 outputs.go:108: INFO Activated elasticsearch as output plugin.
2018/05/15 11:12:40.396802 publish.go:238: DBG  Create output worker
2018/05/15 11:12:40.396843 publish.go:280: DBG  No output is defined to store the topology. The server fields might not be filled.
2018/05/15 11:12:40.396865 publish.go:295: INFO Publisher name: ip-172-16-3-81.ec2.internal
2018/05/15 11:12:40.396998 async.go:63: INFO Flush Interval set to: 1s
2018/05/15 11:12:40.397007 async.go:64: INFO Max Bulk Size set to: 50
2018/05/15 11:12:40.397013 async.go:72: DBG  create bulk processing worker (interval=1s, bulk size=50)
2018/05/15 11:12:40.397124 cloudwatchmetricbeat.go:44: INFO settings: config={Period:1m0s AWSRegion:us-east-1 Prospectors:[{Id:ec2_cloudwatch Metrics:[{AWSStatistics:[Average] AWSDimensions:[InstanceId] AWSDimensionSelect:map[InstanceId:[i-07a27a3fb38cc4683]] AWSDimensionsSelectParam:map[] AWSNamespace:AWS/EC2 AWSMetricName:CPUUtilization RangeSeconds:0 PeriodSeconds:60 DelaySeconds:0}]}]}
2018/05/15 11:12:40.397363 beat.go:221: INFO cloudwatchmetricbeat start running.
2018/05/15 11:12:40.397374 cloudwatchmetricbeat.go:63: INFO cloudwatchmetricbeat is running! Hit CTRL-C to stop it.
2018/05/15 11:12:40.397569 metrics.go:23: INFO Metrics logging every 30s
2018/05/15 11:13:10.397775 metrics.go:34: INFO No non-zero metrics in the last 30s
2018/05/15 11:13:40.398566 metrics.go:34: INFO No non-zero metrics in the last 30s
2018/05/15 11:13:40.460102 cloudwatchmetricbeat.go:194: INFO making request: params={
  Dimensions: [{
      Name: "InstanceId",
      Value: "i-07a27a3fb38cc4683"
    }],
  EndTime: 2018-05-15 11:08:40.397542353 +0000 UTC,
  MetricName: "CPUUtilization",
  Namespace: "AWS/EC2",
  Period: 60,
  StartTime: 2018-05-15 10:58:40.397542353 +0000 UTC,
  Statistics: ["Average"]
}
2018/05/15 11:13:40.460227 client.go:214: DBG  Publish: {
  "@timestamp": "2018-05-15T11:06:00.000Z",
  "beat": {
    "hostname": "ip-172-16-3-81.ec2.internal",
    "name": "ip-172-16-3-81.ec2.internal",
    "version": "5.3.4"
  },
  "cloudwatchset.name": "ec2_cloudwatch",
  "cloudwatchset.namespace": "AWS/EC2",
  "cloudwatchset.resource_id": "i-07a27a3fb38cc4683",
  "cloudwatchset.resource_id_type": "instance_id",
  "cpu_utilization.avg": 0.166667,
  "type": "cloudwatchset"
}
2018/05/15 11:13:40.460289 metrics.go:51: INFO Total non-zero values:  libbeat.publisher.messages_in_worker_queues=1 libbeat.publisher.published_events=1
2018/05/15 11:13:40.460298 metrics.go:52: INFO Uptime: 1m0.06759237s
2018/05/15 11:13:40.460303 beat.go:225: INFO cloudwatchmetricbeat stopped.
```
